services:
  app:
    build: .
    hostname: aws-infrastructure-helper
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PROFILE=${PROFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
